dist: xenial

language: c

env:
  global:
    # Environment variables for ccache
    - CCACHE_COMPRESS=1
    - CCACHE_SLOPPINESS=time_macros,file_macro
    - CCACHE_BASEDIR="$TRAVIS_BUILD_DIR"

jobs:
  include:
    - stage: baseline
      os: linux
      compiler: clang-4.0
    - os: linux
      compiler: gcc

    - stage: second stage
      os: osx
      compiler: clang
      osx_image: xcode10.2 # macOS 10.14
    - os: osx
      compiler: gcc
      osx_image: xcode10.2 # macOS 10.14
  fast_finish: true

script:
  ci/script.sh

addons:
  apt:
    packages:
      - autoconf
      - automake
      - build-essential
      - clang-4.0
      - pkg-config
  homebrew:
    update: true
    packages:
      - ccache

branches:
  only:
    - master
    - /^release-\d+\.\d+$/
    - autoconf

cache:
  apt: true
  ccache: true
